[tool.basedpyright]
include = ["."]
exclude = ["**/__pycache__"]
ignore = ["weechat.pyi"]

reportMissingImports = true
reportMissingTypeStubs = true
reportUnusedCallResult = false

pythonVersion = "3.12"
pythonPlatform = "MacOS"
